### ISSUE TITLE
你好,我是YoungLee-Coder

### ISSUE THREAD

**Issue by YoungLee-coder** [iFulling/cdcasSK#1]
你好,我是YoungLee-Coder,很高兴看的你的脚本,帮助我们进一步实现网课自由,但是我有一些问题想请教,可否给我联系方式
感谢

**Comment by iFulling** [comment]
q 2435406817

**Comment by iFulling** [comment]
> 你好，我是YoungLee-Coder，很高兴看的你的脚本，帮助我们进一步实现网课自由，但是我有一些问题想请教，可否给我联系方式 感谢

q 2435406817

**Comment by Khal1lF0ng** [comment]
> 你好，我是YoungLee-Coder，很高兴看的你的脚本，帮助我们进一步实现网课自由，但是我有一些问题想请教，可否给我联系方式 感谢



> 你好,我是YoungLee-Coder,很高兴看的你的脚本,帮助我们进一步实现网课自由,但是我有一些问题想请教,可否给我联系方式 感谢
学长有考虑做新网站的脚本吗？可恶的CDCAS又更新了一个网站
